# About this notebook

In this notebook, we solve the loop closure equation numerically using `fsolve`.

In [11]:
##### Initial Notebook Setup ####

#Setup so that all output in a cell are printed and not just the last line
    #Source: http://stackoverflow.com/questions/36786722/how-to-display-full-output-in-jupyter-not-only-last-result
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

#Essential things for SymPy
#from sympy import *
#from sympy.abc import *
#init_printing(use_unicode=True)

In [ ]:
THETA = list(symbols('theta1:' + str(6)));
THETA[0] = pi/2;
alpha = pi/4;

a = tan(THETA[1]/2) - tan(THETA[2]/2)*sin(pi/4 + alpha/2)/sin(pi/4-alpha/2);
b = tan(THETA[3]/2)*tan(THETA[4]/2) - sin(pi/4 + alpha/2)/sin(pi/4-alpha/2);
c = THETA[1] + THETA[4] - 2*pi;
d = THETA[0] + THETA[2] + THETA[3] - 2*pi;

In [ ]:
a
b
c
d

In [ ]:
from sympy import *
#N(pi)
solve((a,b,c,d), THETA[1:])

In [31]:
from scipy import *
from scipy.optimize import fsolve
from math import *
import numpy as np

t1 = pi/2
alpha = pi/4

def equations(p):
    t2, t3, t4, t5 = p
    a = tan(t2/2) - tan(t3/2)*sin(pi/4 + alpha/2)/sin(pi/4-alpha/2);
    b = tan(t4/2)*tan(t5/2) - sin(pi/4 + alpha/2)/sin(pi/4-alpha/2);
    c = t2 + t5 - 2*pi;
    d = t1 + t3 + t4 - 2*pi;
    #a = t1 + t2 + t3 + t4 + t5 - 5
    #b = t2*t3 - 1
    #c = t4*t3 - 1
    #d = t5*t3 - 1
    return (a, b, c, d)

t2, t3, t4, t5 =  fsolve(equations, (1, 1, 1, 1))
np.degrees((t2, t3, t4, t5))
t2, t3, t4, t5 =  fsolve(equations, (0.5,0.5,0.5,0.5))
np.degrees((t2, t3, t4, t5))

t2, t3, t4, t5 =  scipy.optimize.broyden2(equations, (1,1,1,1))
np.degrees((t2, t3, t4, t5))

array([  90.,   45.,  225.,  270.])

array([-270.,   45.,  225.,  630.])

array([  90.00007228,   45.0000367 ,  224.999963  ,  269.99993744])